ShadowMap
GLuint ShadowMap::m_ShadowTexture
Texture where the depth will be rendered to.
Referenced by getShadowTextureID, SetupShadowMap.
GLuint ShadowMap::m_ShadowFBO
Framebuffer object used to created the shadow texture
Referenced by BindShadowFrameBuffer, SetupShadowMap.
GLuint ShadowMap::pingpongFBO[2][2]
GLuint ShadowMap::pingpongDepthbuffers[2][2]
GLfloat ShadowMap::m_SHADOW_WIDTH
Shadow map texture width
Referenced by BindShadowFrameBuffer, SetupShadowMap.
GLfloat ShadowMap::m_SHADOW_HEIGHT
Shadow map texture height
Referenced by BindShadowFrameBuffer, SetupShadowMap.
GLfloat ShadowMap::m_NEAR_SHADOW_PLANE
Near plane of the shadow map bounding box
GLfloat ShadowMap::m_FAR_SHADOW_PLANE
Far plane of the shadow map bounding box
glm::vec3 ShadowMap::m_POSITION
Position of the light in World Space
Referenced by setShadowPosition, SetupShadowMatrices.
glm::vec3 ShadowMap::m_DIRECTION
Direction of the light
Referenced by setShadowDirection, SetupShadowMatrices.
glm::mat4 ShadowMap::m_lightProjection
glm::mat4 ShadowMap::m_lightView
glm::mat4 ShadowMap::m_lightSpaceMatrix
glm::mat4 ShadowMap::m_biasMatrix
ShadowMap::ShadowMap(GLfloat width, GLfloat height, GLfloat near, GLfloat far)
Width of the shadow map texture
Constructor: In the first two arguments takes in the width and height of the shadow map texture The third and fourth argument are used for the shadow map bounding box near and far planes
References SetupShadowMap.
virtual ShadowMap::~ShadowMap()
Destructor
void ShadowMap::BindShadowFrameBuffer(void)
Binds the Shadow Map framebuffer as the current framebuffer, where the depth of the scene will be rendered to.
References m_ShadowFBO, m_SHADOW_WIDTH, m_SHADOW_HEIGHT.
void ShadowMap::UnbindShadowFrameBuffer(void)
Binds the current framebuffer to the default framebuffer
References SetupPingPongFBO.
void ShadowMap::SetupPingPongFBO()
Setups a framebuffer for blurring the shadow map image to be used in variance shadow mapping
Referenced by UnbindShadowFrameBuffer.
void ShadowMap::setShadowPosition(glm::vec3 newPos)
Set the Shadow Map Position
References m_POSITION.
void ShadowMap::setShadowDirection(glm::vec3 newDir)
Set the Shadow Map Direction
References m_DIRECTION.
GLuint ShadowMap::getShadowTextureID(void)
Get the Shadow Map texture Id where the depth from the scene was rendered to.
References m_ShadowTexture.
glm::mat4 ShadowMap::getLightSpaceMatrix(void)
Get the Shadow Map LightSpace ProjectionView Matrix
glm::mat4 ShadowMap::getBiasMatrix(void)
Get the Light/Proj Matrix multiplied by the Bias Matrix
References SetupShadowMatrices, SetupShadowMap.
void ShadowMap::SetupShadowMatrices(void)
Setups the matrices from where the light will be calculated
References m_POSITION, m_DIRECTION.
Referenced by getBiasMatrix.
void ShadowMap::SetupShadowMap(void)
Setups the OpenGL related stuff of the Shadowmap
References m_ShadowFBO, m_ShadowTexture, m_SHADOW_WIDTH, m_SHADOW_HEIGHT.
Referenced by ShadowMap, getBiasMatrix.