.TH "App" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBApp\fP (GLFWwindow *&win)"
.br
.ti -1c
.RI "void \fBRun\fP (void)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBEpsilon\fP > \fBEpsilonEngine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 13 of file main\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
