.TH "BITMAP_INFORMATION_HEADER" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BITMAP_INFORMATION_HEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "INT \fBBITMAPINFOHEADER_SIZE\fP"
.br
.ti -1c
.RI "INT \fBWIDTH\fP"
.br
.ti -1c
.RI "INT \fBHEIGHT\fP"
.br
.ti -1c
.RI "SHORT \fBNUM_PLANES\fP"
.br
.ti -1c
.RI "SHORT \fBBPP\fP"
.br
.ti -1c
.RI "INT \fBCOMPRESSION\fP"
.br
.ti -1c
.RI "INT \fBSIZE\fP"
.br
.ti -1c
.RI "INT \fBHORIZONTAL_RESOLUTION\fP"
.br
.ti -1c
.RI "INT \fBVERTICAL_RESOLUTION\fP"
.br
.ti -1c
.RI "INT \fBNUM_COLORS\fP"
.br
.ti -1c
.RI "INT \fBNUM_IMPORTANT_COLORS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file BMP\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
