.TH "BMP_HEADER" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMP_HEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SHORT \fB_signature\fP"
.br
.ti -1c
.RI "INT \fB_size\fP"
.br
.ti -1c
.RI "SHORT \fB_reserved\fP"
.br
.ti -1c
.RI "SHORT \fB__reserved\fP"
.br
.ti -1c
.RI "INT \fB_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file BMP\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
