.TH "CheckBox" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckBox \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckBox\fP (float width, float height, int winWidth, int winHeight, std::string text)"
.br
.ti -1c
.RI "void \fBfunc\fP ()"
.br
.ti -1c
.RI "const void \fBToggle\fP ()"
.br
.ti -1c
.RI "glm::vec2 \fBCalculateResolution\fP (int w, int h, int ww, int wh)"
.br
.ti -1c
.RI "void \fBRender\fP (std::shared_ptr< \fBShader\fP > shader)"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBsetText\fP (std::string txt)"
.br
.ti -1c
.RI "bool \fBChecked\fP ()"
.br
.ti -1c
.RI "void \fBCheck\fP ()"
.br
.ti -1c
.RI "void \fBUncheck\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBText\fP > \fBm_TextRendererInstance\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fB_checked\fP = true"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::function< void()> \fB_clickfunc\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBeTexture\fP > \fB_checkedIco\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBeTexture\fP > \fB_uncheckedIco\fP"
.br
.ti -1c
.RI "glm::mat4 \fBprojection\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBOpenGLHelpers::Quad\fP > \fBm_Quad\fP"
.br
.ti -1c
.RI "std::string \fB_text\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBm_CheckBoxShader\fP"
.br
.ti -1c
.RI "float \fBm_Width\fP"
.br
.ti -1c
.RI "float \fBm_Height\fP"
.br
.ti -1c
.RI "float \fBm_winWidth\fP"
.br
.ti -1c
.RI "float \fBm_winHeight\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CheckBox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
