.TH "Component::ClothComponent" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Component::ClothComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponent::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClothComponent\fP (std::shared_ptr< \fBCamera\fP > &inPointerToCamera)"
.br
.ti -1c
.RI "void \fBFill\fP (std::shared_ptr< \fBPhysics::PhysicObject\fP > PhysicBodyPointer)"
.br
.ti -1c
.RI "void \fBRender\fP (std::shared_ptr< \fBResourceManager\fP > rm, glm::vec3 pos)"
.br
.ti -1c
.RI "virtual void \fBRenderShadows\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (std::shared_ptr< \fBResourceManager\fP > rm)"
.br
.ti -1c
.RI "void \fBsetShader\fP (std::string sh)"
.br
.ti -1c
.RI "virtual void \fBFill\fP (bool, bool)"
.br
.ti -1c
.RI "virtual void \fBFill\fP (float, std::shared_ptr< \fBPhysics::PhysicObject\fP > PhysicBodyPointer)"
.br
.ti -1c
.RI "virtual void \fBFill\fP (std::string path, std::shared_ptr< \fBResourceManager\fP > &rm, std::string shader)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetTransparency\fP (bool x)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBPatch\fP > \fBmPatch\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBPhysics::PhysicObject\fP > \fBRigidBodyPointer\fP = nullptr"
.br
.ti -1c
.RI "std::shared_ptr< \fBCamera\fP > \fBPointerToCamera\fP"
.br
.ti -1c
.RI "std::string \fBshaderType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 297 of file Component\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Component::ClothComponent::Fill (bool, bool)\fC [inline]\fP, \fC [virtual]\fP"
Functions declared for the sake of pure virtual function polymorphism, must not be used for production 
.PP
Implements \fBComponent::Component\fP\&.
.PP
Definition at line 345 of file Component\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
