.TH "Component::Component" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Component::Component \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBComponent::ClothComponent\fP, \fBComponent::MovementComponent\fP, \fBComponent::PhysicComponent\fP, \fBComponent::PlayerComponent\fP, \fBComponent::RenderComponent\fP, and \fBComponent::SoundComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBFill\fP (bool HasHealth, bool HasGun)=0"
.br
.ti -1c
.RI "virtual void \fBFill\fP (std::string path, std::shared_ptr< \fBResourceManager\fP > &rm, std::string shader)=0"
.br
.ti -1c
.RI "virtual void \fBFill\fP (float mass, std::shared_ptr< \fBPhysics::PhysicObject\fP > PhysicBodyPointer)=0"
.br
.ti -1c
.RI "virtual void \fBsetUserPointer\fP (void *userPointer)"
.br
.ti -1c
.RI "virtual btTransform \fBgetTransform\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetTransform\fP (btTransform)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (std::shared_ptr< \fBResourceManager\fP > rm)=0"
.br
.ti -1c
.RI "virtual void \fBRender\fP (std::shared_ptr< \fBResourceManager\fP > rm, glm::vec3)=0"
.br
.ti -1c
.RI "virtual void \fBRenderShadows\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetTransparency\fP (bool x)=0"
.br
.ti -1c
.RI "void \fBsetShader\fP (string sh)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "COMPONENT_TYPE \fBType\fP"
.br
.ti -1c
.RI "btVector3 \fBm_PhysicsWorldPosition\fP"
.br
.ti -1c
.RI "btVector3 \fBm_LastPhysicsWorldPosition\fP"
.br
.ti -1c
.RI "btVector3 \fBm_PhysicsWorldScale\fP"
.br
.ti -1c
.RI "btQuaternion \fBm_PhysicsWorldRotation\fP"
.br
.ti -1c
.RI "btQuaternion \fBm_LastPhysicsWorldRotation\fP"
.br
.ti -1c
.RI "bool \fBupdateIfOutOfView\fP = true"
.br
.ti -1c
.RI "bool \fBisTransparent\fP = false"
.br
.ti -1c
.RI "bool \fBisDoubleFaced\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Component\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
