.TH "Console::Line" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console::Line \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBColor\fP = glm::vec3"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLine\fP (std::string content, Color col)"
.br
.ti -1c
.RI "std::string const \fBgetText\fP ()"
.br
.ti -1c
.RI "Color const \fBgetColor\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmContent\fP"
.br
.ti -1c
.RI "Color \fBmColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Console\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
