.TH "Container" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Container \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBaddWidget\fP (std::shared_ptr< \fBWidget\fP > widget)"
.br
.ti -1c
.RI "void \fBRender\fP (std::shared_ptr< \fBShader\fP > shader)"
.br
.ti -1c
.RI "void \fBAnalizeEvents\fP (\fBGUIEVENTS\fP Events)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBWidget\fP > > \fBm_WidgetContainer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Container\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
