.TH "DDS_HEADER" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DDS_HEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdwSize\fP"
.br
.ti -1c
.RI "int \fBdwFlags\fP"
.br
.ti -1c
.RI "int \fBdwHeight\fP"
.br
.ti -1c
.RI "int \fBdwWidth\fP"
.br
.ti -1c
.RI "int \fBdwPitchOrLinearSize\fP"
.br
.ti -1c
.RI "int \fBdwDepth\fP"
.br
.ti -1c
.RI "int \fBdwMipMapCount\fP"
.br
.ti -1c
.RI "int \fBdwReserved1\fP [11]"
.br
.ti -1c
.RI "\fBDDS_PIXELFORMAT\fP \fBddspf\fP"
.br
.ti -1c
.RI "int \fBdwCaps\fP"
.br
.ti -1c
.RI "int \fBdwCaps2\fP"
.br
.ti -1c
.RI "int \fBdwCaps3\fP"
.br
.ti -1c
.RI "int \fBdwCaps4\fP"
.br
.ti -1c
.RI "int \fBdwReserved2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file DDSFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
