.TH "EntityTemplate" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityTemplate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityTemplate\fP (std::shared_ptr< \fBResourceManager\fP > rm, glm::vec3 pos, glm::vec3 sc, glm::quat rot)"
.br
.ti -1c
.RI "void \fBaddComponent\fP (std::shared_ptr< \fBComponent::Component\fP > t)"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.ti -1c
.RI "void \fBRenderShadows\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetPosition\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetPrevPosition\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetScale\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetPrevScale\fP ()"
.br
.ti -1c
.RI "glm::quat \fBgetRotation\fP ()"
.br
.ti -1c
.RI "glm::quat \fBgetPrevRotation\fP ()"
.br
.ti -1c
.RI "\fBMIN_MAX_POINTS\fP \fBgetBoundingBox\fP ()"
.br
.ti -1c
.RI "long \fBtoHash\fP ()"
.br
.ti -1c
.RI "void \fBsetShader\fP (std::string sh)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhasPlayerComponent\fP = false"
.br
.ti -1c
.RI "bool \fBhasModel\fP = false"
.br
.ti -1c
.RI "bool \fBhasPhysicComponent\fP = false"
.br
.ti -1c
.RI "bool \fBhasClothComponent\fP = false"
.br
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "std::string \fBmodelPath\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBComponent::Component\fP > > \fBComponentList\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBm_Position\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_Scale\fP"
.br
.ti -1c
.RI "glm::quat \fBm_Rotation\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_PrevPosition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_PrevScale\fP"
.br
.ti -1c
.RI "glm::quat \fBm_PrevRotation\fP"
.br
.ti -1c
.RI "\fBPhysics::CollisionInfo\fP \fBCollInfo\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBResourceManager\fP > \fBresourceManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file EntityTemplate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
