.TH "Global::Log" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Global::Log \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOpenFile\fP (std::string path)"
.br
.ti -1c
.RI "static void \fBWriteToLog\fP (std::string logmesage)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::ofstream \fBFILE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Log\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
