.TH "Helpers::ElapsedTime" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helpers::ElapsedTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElapsedTime\fP (float maxTimeStep=0\&.03333f)"
.br
.ti -1c
.RI "float \fBGetElapsedTime\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_fMaxTimeStep\fP"
.br
.ti -1c
.RI "float \fBm_fPrevious\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file Includes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
