.TH "Input::KeyBoard" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input::KeyBoard \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBKeyBoardCallBack\fP (GLFWwindow *window, int key, int scancode, int action, int mode)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBKEYS\fP [1024] = {false}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file KeyBoard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
