.TH "IO::Audio::AudioListener" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Audio::AudioListener \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateListener\fP ()"
.br
.ti -1c
.RI "void \fBsetListenerPosition\fP (glm::vec3 pos)"
.br
.ti -1c
.RI "void \fBsetListenerDirection\fP (glm::vec3 dir)"
.br
.ti -1c
.RI "glm::vec3 \fBgetListenerPosition\fP () const "
.br
.ti -1c
.RI "glm::vec3 \fBgetListenerDirection\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBm_ListenerPosition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_ListenerDirection\fP"
.br
.ti -1c
.RI "float \fBm_ListenerOrientation\fP [6]"
.br
.ti -1c
.RI "float \fBm_ListenerVelocity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file AudioListener\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
