.TH "IO::Audio::File::WAVfile" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Audio::File::WAVfile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::shared_ptr< char > \fBLoad\fP (const char *fn)"
.br
.ti -1c
.RI "int \fBgetNumberOfChannels\fP ()"
.br
.ti -1c
.RI "int \fBgetSampleRate\fP ()"
.br
.ti -1c
.RI "int \fBgetBPS\fP ()"
.br
.ti -1c
.RI "int \fBgetFileSize\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBchan\fP"
.br
.ti -1c
.RI "int \fBsamplerate\fP"
.br
.ti -1c
.RI "int \fBbps\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file WAVFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
