.TH "IO::Filesystem::VirtualFileSystem" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Filesystem::VirtualFileSystem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBIO::Filesystem::PhysicalFileSystem\fP, and \fBIO::Filesystem::ZipFileSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBFile\fP \fBFindFile\fP (const std::string)=0"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_IsZip\fP"
.br
.ti -1c
.RI "std::string \fBm_Path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file filesystem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
