.TH "IO::Filesystem::File" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Filesystem::File \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBgenerateHash\fP (std::string filename)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "uint32_t \fBhash\fP"
.br
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file filesystem\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t IO::Filesystem::File::generateHash (std::string filename)"
Theorical definition of a file including a hash in case it is inside a zip file and the name of the file itself 
.PP
Definition at line 13 of file filesystem\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
