.TH "IO::Image::DDS" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Image::DDS \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDDS\fP (std::string)"
.br
.ti -1c
.RI "const \fBDDS_HEADER\fP * \fBheader\fP () const "
.br
.ti -1c
.RI "const std::shared_ptr< unsigned char > \fBData\fP () const "
.br
.ti -1c
.RI "const unsigned int \fBInternalFormat\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDDS_HEADER\fP * \fB_header\fP"
.br
.ti -1c
.RI "std::shared_ptr< unsigned char > \fBdata\fP"
.br
.ti -1c
.RI "unsigned int \fBm_InternalFormat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file DDS\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
