.TH "MD5Animation::FrameData" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD5Animation::FrameData \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBm_iFrameID\fP"
.br
.ti -1c
.RI "std::vector< float > \fBm_FrameData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file MD5_Anim\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
