.TH "MD5Model::Joint" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD5Model::Joint \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_Name\fP"
.br
.ti -1c
.RI "int \fBm_ParentID\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_Pos\fP"
.br
.ti -1c
.RI "glm::quat \fBm_Orient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file MD5_Model\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
