.TH "MD5Model::Mesh" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MD5Model::Mesh \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBm_Shader\fP"
.br
.ti -1c
.RI "VertexList \fBm_Verts\fP"
.br
.ti -1c
.RI "TriangleList \fBm_Tris\fP"
.br
.ti -1c
.RI "WeightList \fBm_Weights\fP"
.br
.ti -1c
.RI "glm::mat4 \fBm_BindPoseMatrix\fP"
.br
.ti -1c
.RI "GLuint \fBm_TexID\fP"
.br
.ti -1c
.RI "GLuint \fBm_nTexID\fP"
.br
.ti -1c
.RI "GLuint \fBm_sTexID\fP"
.br
.ti -1c
.RI "GLuint \fBm_mTexID\fP"
.br
.ti -1c
.RI "PositionBuffer \fBm_PositionBuffer\fP"
.br
.ti -1c
.RI "NormalBuffer \fBm_NormalBuffer\fP"
.br
.ti -1c
.RI "TangentBuffer \fBm_TangentBuffer\fP"
.br
.ti -1c
.RI "BinormalBuffer \fBm_BinormalBuffer\fP"
.br
.ti -1c
.RI "Tex2DBuffer \fBm_Tex2DBuffer\fP"
.br
.ti -1c
.RI "IndexBuffer \fBm_IndexBuffer\fP"
.br
.ti -1c
.RI "WeightBuffer \fBm_BoneWeights\fP"
.br
.ti -1c
.RI "BoneIndexBuffer \fBm_BoneIndex\fP"
.br
.ti -1c
.RI "GLuint \fBm_VAO\fP"
.br
.ti -1c
.RI "GLuint \fBm_VBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_NBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_TBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_BBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_WBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_IBBO\fP"
.br
.ti -1c
.RI "GLuint \fBm_IBO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file MD5_Model\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
