.TH "MIN_MAX_POINTS" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MIN_MAX_POINTS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBMAX_X\fP"
.br
.ti -1c
.RI "float \fBMAX_Y\fP"
.br
.ti -1c
.RI "float \fBMAX_Z\fP"
.br
.ti -1c
.RI "float \fBMIN_X\fP"
.br
.ti -1c
.RI "float \fBMIN_Y\fP"
.br
.ti -1c
.RI "float \fBMIN_Z\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file Types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
