.TH "ParticleProxy" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMistParticleProxy\fP, \fBRainParticleProxy\fP, \fBSmokeParticleProxy\fP, and \fBSnowParticleProxy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleProxy\fP (unsigned int id, \fBMINMAX_POINTS\fP limits, double numparts)"
.br
.ti -1c
.RI "virtual void \fBSimulate\fP (float, glm::vec3)"
.br
.ti -1c
.RI "virtual void \fBRender\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBm_NumParticles\fP"
.br
.ti -1c
.RI "std::vector< glm::mat4 > \fBm_ParticlePositions\fP"
.br
.ti -1c
.RI "GLuint \fBquadVAO\fP"
.br
.ti -1c
.RI "GLuint \fBquadVBO\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBParticleRenderer\fP > \fBm_ParticleRenderer\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "glm::vec3 \fBGenerateRandomParticle\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitializeProxy\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::random_device \fBrd\fP"
.br
.ti -1c
.RI "std::default_random_engine \fBgenerator\fP"
.br
.ti -1c
.RI "\fBMINMAX_POINTS\fP \fBParticlesLimits\fP"
.br
.ti -1c
.RI "unsigned int \fBID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file ParticleProxy\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
