.TH "ParticleRenderer" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParticleRenderer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticleRenderer\fP (unsigned int ID, unsigned int numParticles, std::vector< glm::mat4 > initPos)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.ti -1c
.RI "void \fBUpdateParticleRenderer\fP (std::vector< glm::mat4 > newPositions)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBGenerateParticleGeometry\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< glm::mat4 > \fBm_Positions\fP"
.br
.ti -1c
.RI "unsigned int \fBm_NumParticles\fP"
.br
.ti -1c
.RI "unsigned int \fBSystem_ID\fP"
.br
.ti -1c
.RI "GLuint \fBVAO\fP"
.br
.ti -1c
.RI "GLuint \fBVBO\fP"
.br
.ti -1c
.RI "GLuint \fBEBO\fP"
.br
.ti -1c
.RI "GLuint \fBPositionBuffer\fP"
.br
.ti -1c
.RI "GLfloat \fBParticleVertices\fP [32]"
.br
.ti -1c
.RI "GLuint \fBParticlesIndices\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ParticleRenderer\&.h\&.
.SH "Field Documentation"
.PP 
.SS "GLuint ParticleRenderer::ParticlesIndices[6]\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
=
    {
        0, 1, 3,
        1, 2, 3,
    }
.fi
.PP
Definition at line 110 of file ParticleRenderer\&.h\&.
.SS "GLfloat ParticleRenderer::ParticleVertices[32]\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
=
    {
        0\&.25f,  0\&.25f,  0\&.0f, 1\&.0f, 1\&.0f, 0\&.0, 1\&.0, 0\&.0,
        0\&.25f, -0\&.25f,  0\&.0f, 1\&.0f, 0\&.0f, 0\&.0, 1\&.0, 0\&.0,
        -0\&.25f, -0\&.25f,  0\&.0f, 0\&.0f, 0\&.0f, 0\&.0, 1\&.0, 0\&.0,
        -0\&.25f,  0\&.25f,  0\&.0f, 0\&.0f, 1\&.0f, 0\&.0, 1\&.0, 0\&.0,
    }
.fi
.PP
Definition at line 102 of file ParticleRenderer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
