.TH "Particle" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticle\fP (glm::vec3 pos, float speed, float life, \fBMINMAX_POINTS\fP limits)"
.br
.ti -1c
.RI "const glm::vec3 \fBgetPosition\fP () const "
.br
.ti -1c
.RI "void \fBresetPosition\fP ()"
.br
.ti -1c
.RI "const glm::vec3 \fBgetSpeed\fP () const "
.br
.ti -1c
.RI "void \fBsetSpeed\fP (glm::vec3 sp)"
.br
.ti -1c
.RI "const float \fBgetLife\fP () const "
.br
.ti -1c
.RI "void \fBsetLife\fP (float life)"
.br
.ti -1c
.RI "void \fBresetLife\fP ()"
.br
.ti -1c
.RI "const float \fBgetWeight\fP () const "
.br
.ti -1c
.RI "void \fBsetPosition\fP (const glm::vec3 pos)"
.br
.ti -1c
.RI "void \fBsetDistancetoCamera\fP (float dist)"
.br
.ti -1c
.RI "const float \fBgetDistancetoCamera\fP () const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBParticle\fP &that) const "
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBm_Position\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_Direction\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBm_Speed\fP"
.br
.ti -1c
.RI "float \fBm_Life\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_InitialPosition\fP"
.br
.ti -1c
.RI "\fBMINMAX_POINTS\fP \fBParticlesLimits\fP"
.br
.ti -1c
.RI "float \fBm_InitialLife\fP"
.br
.ti -1c
.RI "float \fBm_Weight\fP"
.br
.ti -1c
.RI "float \fBm_DistancetoCamera\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Particle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
