.TH "Physics::PhysicObject::t_Face" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::PhysicObject::t_Face \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_Vertex\fP \fBvextex0\fP"
.br
.ti -1c
.RI "\fBt_Vertex\fP \fBvextex1\fP"
.br
.ti -1c
.RI "\fBt_Vertex\fP \fBvextex2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file PhysicObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
