.TH "Physics::PhysicObject" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::PhysicObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhysics::ClothPhysicObject\fP, \fBPhysics::CubePhysicObject\fP, \fBPhysics::SpherePhysicObject\fP, and \fBPhysics::TriangleMeshPhysicObject\fP\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBt_ClothVertex\fP"
.br
.ti -1c
.RI "struct \fBt_Face\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (glm::vec3, float, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (float, float, float, float, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (float, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (glm::vec3, float, \fBMIN_MAX_POINTS\fP, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (std::vector< glm::vec3 >, std::vector< unsigned int >, float)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< btRigidBody > \fBBody\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file PhysicObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
