.TH "Physics::ClothPhysicObject" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::ClothPhysicObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhysics::PhysicObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< btSoftBody > \fBaddObject\fP (std::shared_ptr< btSoftBodyWorldInfo > softWorldInfo, const glm::vec3 position, const btScalar s, const int numX, const int numY, const int fixed)"
.br
.ti -1c
.RI "std::vector< \fBt_ClothVertex\fP > \fBgetVertices\fP ()"
.br
.ti -1c
.RI "float \fBgetScale\fP ()"
.br
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "void \fBsetWind\fP (btVector3 direction, float speed)"
.br
.ti -1c
.RI "void \fBsetconstraint\fP (int x, int y)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< btSoftBody > \fBm_BodyCloth\fP"
.br
.ti -1c
.RI "\fBCollisionInfo\fP \fBCollInfo\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBmScale\fP"
.br
.ti -1c
.RI "int \fBmWidth\fP"
.br
.ti -1c
.RI "int \fBmHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file ClothPhysicObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
