.TH "PostProcess::ScreenSpaceReflections" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostProcess::ScreenSpaceReflections \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPostProcess::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenSpaceReflections\fP (int, int)"
.br
.ti -1c
.RI "virtual GLuint \fBApply\fP (GLuint, GLuint, GLuint, GLuint, GLuint, glm::mat4, glm::mat4)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBPrepareSSRTexture\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file ScreenSpaceReflections\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void PostProcess::ScreenSpaceReflections::PrepareSSRTexture ()"

.PP
 SSR Specific Code ---------------------------------------- 
.PP
Definition at line 48 of file ScreenSpaceReflections\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
