.TH "PostProcess::Effect" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostProcess::Effect \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPostProcess::MotionBlur\fP, \fBPostProcess::ScreenSpaceReflections\fP, and \fBPostProcess::SSAO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffect\fP (int, int)"
.br
.ti -1c
.RI "virtual GLuint \fBApply\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBFrameBuffer\fP< std::string > > \fBm_pFrameBuffer\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBOpenGLHelpers::FullScreenQuad\fP > \fBm_pFullScreenQuad\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBm_pShader\fP"
.br
.ti -1c
.RI "int \fBm_Width\fP"
.br
.ti -1c
.RI "int \fBm_Height\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Effect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
