.TH "Renderer" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDeferredRenderer\fP, and \fBDeferredRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()=0"
.br
.ti -1c
.RI "void \fBEnd\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBbeginRender\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBendRender\fP ()=0"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "short \fBWIDTH\fP"
.br
.ti -1c
.RI "short \fBHEIGHT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file renderer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
