.TH "RenderTarget" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderTarget \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderTarget\fP (int width, int height, int internalformat, int format, int magfilter, int minfilter, int attachment, bool mipmaps, GLuint target)"
.br
.ti -1c
.RI "bool \fBDestroyRenderTarget\fP ()"
.br
.ti -1c
.RI "GLuint \fBgetRenderTextureTarget\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBm_RenderTextureTarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file RenderTarget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
