.TH "Sun" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sun \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSun\fP ()"
.br
.ti -1c
.RI "void \fBRender\fP (\fBShader\fP *&)"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSetUniforms\fP (std::shared_ptr< \fBCamera\fP >, \fBShader\fP *&)"
.br
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.ti -1c
.RI "glm::vec3 \fBDirection\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrepareVAO\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBeTexture\fP > \fBtex\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "GLuint \fBTextureID\fP"
.br
.ti -1c
.RI "float \fBmMovement\fP"
.br
.ti -1c
.RI "GLuint \fBVAO\fP"
.br
.ti -1c
.RI "GLuint \fBVBO\fP"
.br
.ti -1c
.RI "GLuint \fBEBO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 19 of file Sun\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sun::Sun ()"
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 10 of file Sun\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Sun::PrepareVAO ()\fC [private]\fP"
Positions /// \fBTexture\fP Coords
.PP
Top Left
.PP
Top Right
.PP
Bottom Right
.PP
Bottom Left 
.PP
Definition at line 71 of file Sun\&.cpp\&.
.SS "void Sun::Update (void)"
glm::cos(glfwGetTime()/10) 
.PP
Definition at line 51 of file Sun\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
