.TH "t_BSPmap" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_BSPmap \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpath\fP [50]"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBrotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file empFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
