.TH "t_emp_header" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_emp_header \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBformat\fP"
.br
.ti -1c
.RI "float \fBversion\fP"
.br
.ti -1c
.RI "int \fBnumLumps\fP"
.br
.ti -1c
.RI "int \fBnumLights\fP"
.br
.ti -1c
.RI "int \fBnumEntities\fP"
.br
.ti -1c
.RI "int \fBnumSounds\fP"
.br
.ti -1c
.RI "int \fBnumParticles\fP"
.br
.ti -1c
.RI "int \fBnumterrains\fP"
.br
.ti -1c
.RI "int \fBnumLightProbes\fP"
.br
.ti -1c
.RI "int \fBnumWaters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file empFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
