.TH "t_light" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_light \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_vector\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBdirection\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "float \fBintensity\fP"
.br
.ti -1c
.RI "glm::vec4 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec4 \fBdirection\fP"
.br
.ti -1c
.RI "glm::vec4 \fBcolor\fP"
.br
.ti -1c
.RI "float \fB_padding\fP [3]"
.br
.ti -1c
.RI "float \fBwatts\fP"
.br
.ti -1c
.RI "float \fB__padding\fP [3]"
.br
.ti -1c
.RI "float \fB___padding\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file empFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
