.TH "t_lightprobe" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_lightprobe \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_vector\fP \fBu_L00\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L1m1\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L10\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L11\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L2m2\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L2m1\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L20\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L21\fP"
.br
.ti -1c
.RI "\fBt_vector\fP \fBu_L22\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file empFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
