.TH "t_Mesh" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_Mesh \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBmMaterial\fP [4][100] = {{0}}"
.br
.ti -1c
.RI "int \fBmNumVertices\fP = 0"
.br
.ti -1c
.RI "int \fBmFirstVertex\fP = 0"
.br
.ti -1c
.RI "int \fBmNumIndices\fP = 0"
.br
.ti -1c
.RI "int \fBmFirstIndex\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file emlFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
