.TH "t_Vertex" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_Vertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_Position\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBt_TexCoord\fP \fBtexcoord\fP"
.br
.ti -1c
.RI "\fBt_Normal\fP \fBnormal\fP"
.br
.ti -1c
.RI "\fBt_Tangent\fP \fBtangent\fP"
.br
.ti -1c
.RI "\fBt_Bitangent\fP \fBbitangent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file emlFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
