.TH "tBSPVertex" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPVertex \- This is our BSP vertex structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBvPosition\fP"
.br
.ti -1c
.RI "glm::vec2 \fBvTextureCoord\fP"
.br
.RI "\fI(x, y, z) position\&. \fP"
.ti -1c
.RI "glm::vec2 \fBvLightmapCoord\fP"
.br
.RI "\fI(u, v) texture coordinate \fP"
.ti -1c
.RI "glm::vec3 \fBvNormal\fP"
.br
.RI "\fI(u, v) lightmap coordinate \fP"
.ti -1c
.RI "char \fBcolor\fP [4]"
.br
.RI "\fI(x, y, z) normal vector \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is our BSP vertex structure\&. 
.PP
Definition at line 57 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
