.TH "tBSPLightmap" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPLightmap \- This is our BSP lightmap structure which stores the 128x128 RGB values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBimageBits\fP [128][128][3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is our BSP lightmap structure which stores the 128x128 RGB values\&. 
.PP
Definition at line 23 of file BSPFace\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
