.TH "tBSPBrush" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPBrush \- This stores the brush data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbrushSide\fP"
.br
.ti -1c
.RI "int \fBnumOfBrushSides\fP"
.br
.RI "\fIThe starting brush side for the brush\&. \fP"
.ti -1c
.RI "int \fBtextureID\fP"
.br
.RI "\fINumber of brush sides for the brush\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This stores the brush data\&. 
.PP
Definition at line 133 of file BSPformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
