.TH "tBSPLump" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPLump \- This is our BSP lump structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.RI "\fIThe offset into the file for the start of this lump\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is our BSP lump structure\&. 
.PP
Definition at line 50 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
