.TH "Text::Character" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text::Character \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GLuint \fBTextureID\fP"
.br
.ti -1c
.RI "glm::ivec2 \fBSize\fP"
.br
.RI "\fIID handle of the glyph texture\&. \fP"
.ti -1c
.RI "glm::ivec2 \fBBearing\fP"
.br
.RI "\fISize of glyph\&. \fP"
.ti -1c
.RI "long int \fBAdvance\fP"
.br
.RI "\fIOffset from baseline to left/top of glyph\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 211 of file Text\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
