.TH "TVertex" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TVertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.RI "\fIPosition\&. \fP"
.ti -1c
.RI "glm::vec2 \fBTexCoords\fP"
.br
.RI "\fITexCoords\&. \fP"
.ti -1c
.RI "glm::vec3 \fBNormal\fP"
.br
.RI "\fINormal\&. \fP"
.ti -1c
.RI "glm::vec3 \fBTangent\fP"
.br
.RI "\fITangent\&. \fP"
.ti -1c
.RI "glm::vec3 \fBBinormal\fP"
.br
.RI "\fIBinormal\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Terrain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
