.TH "VertexArrayObject" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexArrayObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetAttribute\fP (int size, size_t stride, void *pointer)"
.br
.ti -1c
.RI "void \fBaddBuffer\fP (GLenum target, GLsizeiptr size, GLvoid *data, GLenum usage)"
.br
.ti -1c
.RI "void \fBBind\fP ()"
.br
.ti -1c
.RI "void \fBUnbind\fP ()"
.br
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBVertexBufferObject\fP > \fBm_VBOArray\fP"
.br
.ti -1c
.RI "int \fBm_VertexAttributeCounter\fP"
.br
.ti -1c
.RI "GLuint \fBm_Handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file VertexArrayObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
