.TH "Vertex" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex \- Contains all the necessery OpenGL includes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBPosition\fP"
.br
.RI "\fIPosition\&. \fP"
.ti -1c
.RI "glm::vec3 \fBNormal\fP"
.br
.RI "\fINormal\&. \fP"
.ti -1c
.RI "glm::vec2 \fBTexCoords\fP"
.br
.RI "\fITexCoords\&. \fP"
.ti -1c
.RI "glm::vec3 \fBTangent\fP"
.br
.RI "\fITangents\&. \fP"
.ti -1c
.RI "glm::vec3 \fBBitangent\fP"
.br
.RI "\fIBitangents\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains all the necessery OpenGL includes\&. 

GL Includes 
.PP
Definition at line 23 of file Mesh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
