.TH "Widget" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Widget \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBButton\fP, \fBCheckBox\fP, \fBConsole\fP, \fBLabel\fP, and \fBPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBRender\fP (std::shared_ptr< \fBShader\fP >)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (void)"
.br
.ti -1c
.RI "virtual void \fBOnClick\fP (void)"
.br
.ti -1c
.RI "virtual void \fBOnHover\fP (void)"
.br
.ti -1c
.RI "virtual void \fBOnEnter\fP (void)"
.br
.ti -1c
.RI "template<typename T > void \fBOnHoverCallback\fP (T func)"
.br
.ti -1c
.RI "template<typename T > void \fBOnEntering\fP (T func)"
.br
.ti -1c
.RI "template<typename T > void \fBOnLeaving\fP (T func)"
.br
.ti -1c
.RI "template<typename T > void \fBOnClickCallback\fP (T func)"
.br
.ti -1c
.RI "template<typename T > void \fBOnEnterCallback\fP (T func)"
.br
.ti -1c
.RI "template<typename T > void \fBOnKeyCallback\fP (T func)"
.br
.ti -1c
.RI "void \fBChangeVisibility\fP ()"
.br
.ti -1c
.RI "void \fBAnalizeEvents\fP (\fBGUIEVENTS\fP Events)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBm_isHidden\fP = false"
.br
.ti -1c
.RI "glm::vec2 \fBm_Position\fP"
.br
.ti -1c
.RI "float \fBPositionX\fP = 0\&.0"
.br
.ti -1c
.RI "float \fBPositionY\fP = 0\&.0"
.br
.ti -1c
.RI "std::string \fBtextureName\fP"
.br
.ti -1c
.RI "float \fBSizeX\fP = 0\&.2"
.br
.ti -1c
.RI "float \fBSizeY\fP = 0\&.2"
.br
.ti -1c
.RI "GUIType \fBtype\fP"
.br
.ti -1c
.RI "float \fBTextSize\fP"
.br
.ti -1c
.RI "float \fBtextPosition\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::function< void()> \fBm_OnClickFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnHoverFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnLostFocusFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnEnteringFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnLeavingFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnEnterFunc\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_OnKeyFunc\fP = nullptr"
.br
.ti -1c
.RI "\fBGUIEVENTS\fP \fBm_Events\fP"
.br
.ti -1c
.RI "float \fBL\fP"
.br
.ti -1c
.RI "float \fBR\fP"
.br
.ti -1c
.RI "float \fBT\fP"
.br
.ti -1c
.RI "float \fBB\fP"
.br
.ti -1c
.RI "float \fBBBL\fP"
.br
.ti -1c
.RI "float \fBBBR\fP"
.br
.ti -1c
.RI "float \fBBBT\fP"
.br
.ti -1c
.RI "float \fBBBB\fP"
.br
.ti -1c
.RI "bool \fBisHover\fP = false"
.br
.ti -1c
.RI "bool \fBwasHover\fP = false"
.br
.ti -1c
.RI "bool \fBhasLostFocus\fP = true"
.br
.ti -1c
.RI "bool \fBWasFocus\fP = true"
.br
.ti -1c
.RI "bool \fBEntering\fP = false"
.br
.ti -1c
.RI "bool \fBLeaving\fP = false"
.br
.ti -1c
.RI "float \fBWIDTH\fP"
.br
.ti -1c
.RI "float \fBHEIGHT\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "glm::vec4 \fBgetBoundingBox\fP ()"
.br
.ti -1c
.RI "void \fBCalculateBorders\fP ()"
.br
.ti -1c
.RI "void \fBCalculateBoundingBox\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Widget\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Widget::AnalizeEvents (\fBGUIEVENTS\fP Events)\fC [inline]\fP"
TOP LEFT
.PP
BOTTOM LEFT
.PP
TOP RIGHT
.PP
BOTTOM RIGHT 
.PP
Definition at line 66 of file Widget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
