# CMake generated Testfile for 
# Source directory: /home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf
# Build directory: /home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-perf_matrix_div "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_matrix_div")
set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;1;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
add_test(test-perf_matrix_inverse "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_matrix_inverse")
set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;2;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
add_test(test-perf_matrix_mul "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_matrix_mul")
set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;3;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
add_test(test-perf_matrix_mul_vector "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_matrix_mul_vector")
set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;4;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
add_test(test-perf_matrix_transpose "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_matrix_transpose")
set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;5;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
add_test(test-perf_vector_mul_matrix "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm-build/test/perf/test-perf_vector_mul_matrix")
set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/CMakeLists.txt;231;add_test;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;6;glmCreateTestGTC;/home/solaire/Documents/Code/C++/Epsilon-Engine/android-build/glm-prefix/src/glm/test/perf/CMakeLists.txt;0;")
