.TH "BSPFace::t_Vertex" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSPFace::t_Vertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "glm::vec2 \fBtexcoord\fP"
.br
.ti -1c
.RI "glm::vec3 \fBnormal\fP"
.br
.ti -1c
.RI "glm::vec3 \fBtangent\fP"
.br
.ti -1c
.RI "glm::vec3 \fBbitangent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file BSPFace\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
