.TH "CFrustum" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFrustum \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCalculateFrustum\fP (glm::mat4 ProjectionMatrix, glm::mat4 ModelMatrix)"
.br
.ti -1c
.RI "bool \fBPointInFrustum\fP (float x, float y, float z)"
.br
.ti -1c
.RI "bool \fBSphereInFrustum\fP (float x, float y, float z, float radius)"
.br
.ti -1c
.RI "bool \fBCubeInFrustum\fP (float x, float y, float z, float size)"
.br
.ti -1c
.RI "bool \fBBoxInFrustum\fP (float x, float y, float z, float sizeX, float sizeY, float sizeZ)"
.br
.ti -1c
.RI "bool \fBBoxInFrustum\fP (\fBMIN_MAX_POINTS\fP points)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_Frustum\fP [6][4] = {{1}, {1}}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Frustum\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CFrustum::BoxInFrustum (float x, float y, float z, float sizeX, float sizeY, float sizeZ)"
Go through all of the corners of the box and check then again each plane in the frustum\&. If all of them are behind one of the planes, then it most like is not in the frustum\&.
.PP
If we get here, it isn't in the frustum 
.PP
Definition at line 282 of file Frustum\&.cpp\&.
.SS "bool CFrustum::BoxInFrustum (\fBMIN_MAX_POINTS\fP points)"
Go through all of the corners of the box and check then again each plane in the frustum\&. If all of them are behind one of the planes, then it most like is not in the frustum\&.
.PP
If we get here, it isn't in the frustum 
.PP
Definition at line 306 of file Frustum\&.cpp\&.
.SS "void CFrustum::CalculateFrustum (glm::mat4 ProjectionMatrix, glm::mat4 ModelMatrix)"
Normalize the BOTTOM side
.PP
This will extract the TOP side of the frustum
.PP
Normalize the TOP side
.PP
This will extract the BACK side of the frustum
.PP
Normalize the BACK side
.PP
Normalize the FRONT side 
.PP
Definition at line 67 of file Frustum\&.cpp\&.
.SS "bool CFrustum::CubeInFrustum (float x, float y, float z, float size)"
Basically, what is going on is, that we are given the center of the cube, and half the length\&. Think of it like a radius\&. Then we checking each point in the cube and seeing if it is inside the frustum\&. If a point is found in front of a side, then we skip to the next side\&. If we get to a plane that does NOT have a point in front of it, then it will return false\&.
.PP
\fINote\fP - This will sometimes say that a cube is inside the frustum when it isn't\&. This happens when all the corners of the bounding box are not behind any one plane\&. This is rare and shouldn't effect the overall rendering speed\&.
.PP
If we get here, it isn't in the frustum 
.PP
Definition at line 236 of file Frustum\&.cpp\&.
.SS "bool CFrustum::PointInFrustum (float x, float y, float z)"
The code below will allow us to make checks within the frustum\&. For example, if we want to see if a point, a sphere, or a cube lies inside of the frustum\&. Because all of our planes point INWARDS (The normals are all pointing inside the frustum) we then can assume that if a point is in FRONT of all of the planes, it's inside\&. Go through all the sides of the frustum
.PP
Calculate the plane equation and check if the point is behind a side of the frustum
.PP
The point was behind a side, so it ISN'T in the frustum
.PP
The point was inside of the frustum (In front of ALL the sides of the frustum) 
.PP
Definition at line 189 of file Frustum\&.cpp\&.
.SS "bool CFrustum::SphereInFrustum (float x, float y, float z, float radius)"
Go through all the sides of the frustum
.PP
If the center of the sphere is farther away from the plane than the radius
.PP
The distance was greater than the radius so the sphere is outside of the frustum 
.PP
Definition at line 213 of file Frustum\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
