.TH "Component" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Component \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClothComponent\fP"
.br
.ti -1c
.RI "class \fBComponent\fP"
.br
.ti -1c
.RI "class \fBMovementComponent\fP"
.br
.ti -1c
.RI "class \fBPhysicComponent\fP"
.br
.RI "\fIPhysic Components\&. \fP"
.ti -1c
.RI "class \fBPlayerComponent\fP"
.br
.RI "\fINPC/Player Components\&. \fP"
.ti -1c
.RI "class \fBRenderComponent\fP"
.br
.RI "\fIRendering Components\&. \fP"
.ti -1c
.RI "class \fBSoundComponent\fP"
.br
.RI "\fIRendering Components\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCOMPONENT_TYPE\fP { \fBMODELCOMPONENT\fP = 0, \fBSPATIALCOMPONENT\fP, \fBPLAYERCOMPONENT\fP, \fBSOUNDCOMPONENT\fP, \fBPHYSICCOMPONENT\fP, \fBCLOTHCOMPONENT\fP }"
.br
.ti -1c
.RI "enum \fBMATERIAL\fP { \fBDIRT\fP = 0, \fBGRAVE\fP, \fBSTONE\fP, \fBMETAL\fP, \fBMUD\fP, \fBWATER\fP, \fBWOOD\fP, \fBCONCRETE\fP, \fBGRASS\fP, \fBOREO\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
