.TH "Component::PlayerComponent" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Component::PlayerComponent \- NPC/Player Components\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComponent::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFill\fP (bool HasHealth, bool HasGun)"
.br
.ti -1c
.RI "void \fBUpdate\fP (std::shared_ptr< \fBResourceManager\fP > rm)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhasHealth\fP"
.br
.ti -1c
.RI "bool \fBhasGun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
NPC/Player Components\&. 
.PP
Definition at line 58 of file Component\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
