.TH "Console" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWidget\fP\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLine\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsole\fP (int w, int h, int fs, glm::vec4 c)"
.br
.ti -1c
.RI "\fBRender\fP ()"
.br
.ti -1c
.RI "\fBToggle\fP ()"
.br
.ti -1c
.RI "\fBAddCommand\fP ()"
.br
.ti -1c
.RI "\fBExecuteCommand\fP ()"
.br
.ti -1c
.RI "bool \fBisShowing\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBRenderFrame\fP ()"
.br
.ti -1c
.RI "void \fBRenderScrollBar\fP ()"
.br
.ti -1c
.RI "void \fBRenderText\fP ()"
.br
.ti -1c
.RI "void \fBRenderInputText\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBmShowing\fP = false"
.br
.ti -1c
.RI "std::vector< \fBLine\fP > \fBmLines\fP"
.br
.ti -1c
.RI "std::string \fBmInput\fP"
.br
.ti -1c
.RI "int \fBmWidth\fP"
.br
.ti -1c
.RI "int \fBmHeight\fP"
.br
.ti -1c
.RI "int \fBmFontSize\fP"
.br
.ti -1c
.RI "glm::vec4 \fBmBackgroundColor\fP"
.br
.ti -1c
.RI "glm::mat4 \fBprojection\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBOpenGLHelpers::Quad\fP > \fBm_Quad\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file Console\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
