.TH "CubemapRenderer" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CubemapRenderer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBegin\fP (int, GLuint, GLuint)"
.br
.ti -1c
.RI "void \fBEnd\fP (int)"
.br
.ti -1c
.RI "std::vector< GLuint > \fBgetRenderTargets\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBmMainShader\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBCopyTexture\fP (int)"
.br
.ti -1c
.RI "void \fBsetCamera\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBmNEAR\fP"
.br
.ti -1c
.RI "float \fBmFAR\fP"
.br
.ti -1c
.RI "int \fBmWIDTH\fP"
.br
.ti -1c
.RI "int \fBmHEIGHT\fP"
.br
.ti -1c
.RI "glm::vec3 \fBmPosition\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBFrameBuffer\fP< int > > \fBmFrameBuffer\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBFrameBuffer\fP< int > > \fBmCopyTextureFrameBuffer\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBOpenGLHelpers::FullScreenQuad\fP > \fBmFullScreenQuad\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBmPassThroughShader\fP"
.br
.ti -1c
.RI "std::vector< GLuint > \fBmRenderTargets\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBCamera\fP > \fBmRendererCamera\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file cubemapRenderer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CubemapRenderer::Begin (int index, GLuint texture, GLuint FBO)"
Function receives the current faces' index 
.PP
Definition at line 19 of file cubemapRenderer\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
