.TH "DDS_PIXELFORMAT" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DDS_PIXELFORMAT \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdwSize\fP"
.br
.ti -1c
.RI "int \fBdwFlags\fP"
.br
.ti -1c
.RI "int \fBdwFourCC\fP"
.br
.ti -1c
.RI "int \fBdwRGBBitCount\fP"
.br
.ti -1c
.RI "int \fBdwRBitMask\fP"
.br
.ti -1c
.RI "int \fBdwGBitMask\fP"
.br
.ti -1c
.RI "int \fBdwBBitMask\fP"
.br
.ti -1c
.RI "int \fBdwABitMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file DDSFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
