.TH "eTexture" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eTexture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeTexture\fP (const char *TexName, GLenum wrap=GL_REPEAT, GLenum type=GL_TEXTURE_2D, GLuint filtering=\-1)"
.br
.ti -1c
.RI "\fBeTexture\fP (std::vector< std::string > CubeMapPath)"
.br
.ti -1c
.RI "void \fBcreateNullTexture\fP (const char *TexName, GLenum wrap=GL_REPEAT, GLenum type=GL_TEXTURE_2D, GLuint filtering=\-1)"
.br
.ti -1c
.RI "void \fBcreateGLTexture\fP (unsigned char *image, const char *TexName, GLenum wrap=GL_REPEAT, GLenum type=GL_TEXTURE_2D, GLuint filtering=\-1)"
.br
.ti -1c
.RI "void \fBloadFile\fP (const char *path, unsigned char *&data, int *outwidth, int *outheight, int *outchannels)"
.br
.ti -1c
.RI "bool \fBisNormal\fP (const char *TexName)"
.br
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.ti -1c
.RI "GLuint \fBgetTextureID\fP (void)"
.br
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "const char * \fBgetPath\fP ()"
.br
.ti -1c
.RI "void \fBsetRequestCount\fP ()"
.br
.ti -1c
.RI "void \fBresetRequestCount\fP ()"
.br
.ti -1c
.RI "int \fBgetTimesUsed\fP ()"
.br
.ti -1c
.RI "long \fBtoHash\fP ()"
.br
.ti -1c
.RI "void \fBcheckLoading\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBtexture\fP = 0"
.br
.ti -1c
.RI "bool \fBispng\fP = false"
.br
.ti -1c
.RI "bool \fBmLoaded\fP = false"
.br
.ti -1c
.RI "std::shared_ptr< \fBIO::Image::Image\fP > \fBmImage\fP = nullptr"
.br
.ti -1c
.RI "unsigned char * \fBimage\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "int \fBm_TimesUsed\fP = 0"
.br
.ti -1c
.RI "double \fBm_TimeSinceLastUse\fP = 0\&.0"
.br
.ti -1c
.RI "int \fBwidth\fP = 0"
.br
.ti -1c
.RI "int \fBheight\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Texture\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
