.TH "Face" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Face \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBvertex0\fP"
.br
.ti -1c
.RI "glm::vec3 \fBvertex1\fP"
.br
.ti -1c
.RI "glm::vec3 \fBvertex2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file Terrain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
