.TH "FrameBuffer< T >" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameBuffer< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameBuffer\fP (int width, int height, bool DepthAttachment)"
.br
.ti -1c
.RI "bool \fBaddRenderTarget\fP (T name, int internalformat, int format, int magfilter, int minfilter, bool mipmaps, GLuint target=GL_TEXTURE_2D)"
.br
.ti -1c
.RI "bool \fBFinishFrameBuffer\fP ()"
.br
.ti -1c
.RI "bool \fBaddDepthAttachment\fP ()"
.br
.ti -1c
.RI "void \fBbindFramebuffer\fP ()"
.br
.ti -1c
.RI "void \fBunbindFramebuffer\fP ()"
.br
.ti -1c
.RI "void \fBsetViewport\fP ()"
.br
.ti -1c
.RI "void \fBclearBuffer\fP (int masks)"
.br
.ti -1c
.RI "void \fBUpdateMipMaps\fP ()"
.br
.ti -1c
.RI "void \fBsetToRead\fP ()"
.br
.ti -1c
.RI "void \fBsetToDraw\fP ()"
.br
.ti -1c
.RI "bool \fBcheckFramebuffer\fP ()"
.br
.ti -1c
.RI "bool \fBDestroy\fP ()"
.br
.ti -1c
.RI "GLuint \fBgetRenderTargetHandler\fP (T name)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::unordered_map< T, std::shared_ptr< \fBRenderTarget\fP > > \fBm_RenderTargets\fP"
.br
.ti -1c
.RI "int \fBm_RenderTargetCount\fP"
.br
.ti -1c
.RI "int \fBMAX_RENDER_TARGETS\fP"
.br
.ti -1c
.RI "int \fBWIDTH\fP"
.br
.ti -1c
.RI "int \fBHEIGHT\fP"
.br
.ti -1c
.RI "GLuint \fBm_FramebufferHandler\fP"
.br
.ti -1c
.RI "GLuint \fBm_DepthTextureTarget\fP"
.br
.ti -1c
.RI "bool \fBisDepthAttachment\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class FrameBuffer< T >"

.PP
Definition at line 11 of file FrameBuffer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
