.TH "glCache" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glCache \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBglUseProgram\fP (GLuint program)"
.br
.ti -1c
.RI "static void \fBglCullFace\fP (GLenum mode)"
.br
.ti -1c
.RI "static void \fBglEnable\fP (GLenum cap)"
.br
.ti -1c
.RI "static void \fBglDrawElements\fP (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)"
.br
.ti -1c
.RI "static void \fBglDrawArrays\fP (GLenum mode, GLint first, GLsizei count)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GLuint \fBShaderId\fP = 0"
.br
.ti -1c
.RI "static GLenum \fBCullFaceMode\fP = 0"
.br
.ti -1c
.RI "static unsigned \fBDrawCalls\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file GlCache\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
