.TH "GLSLPreProcessor::sDirective" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLSLPreProcessor::sDirective \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBmacro\fP"
.br
.ti -1c
.RI "std::string \fBdirective\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ShaderPreProcessor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
