.TH "GPU" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPU \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetDriverVersion\fP ()"
.br
.ti -1c
.RI "std::string \fBgetVendor\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDevice\fP ()"
.br
.ti -1c
.RI "size_t \fBgetAvailableMemory\fP ()"
.br
.ti -1c
.RI "size_t \fBgetTotalMemory\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmVendor\fP"
.br
.ti -1c
.RI "std::string \fBmDriverVersion\fP"
.br
.ti -1c
.RI "std::string \fBmDevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file GPU\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
