.TH "GUI" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGUI\fP (int winWidth, int winHeight)"
.br
.ti -1c
.RI "void \fBRender\fP ()"
.br
.ti -1c
.RI "bool \fBAddContainer\fP (std::shared_ptr< \fBContainer\fP > container)"
.br
.ti -1c
.RI "bool \fBGUIRemoveWidget\fP (int WidgetID)"
.br
.ti -1c
.RI "void \fBPollEvents\fP (GLFWwindow *window)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBContainer\fP > > \fBm_ContainerCollection\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBm_Shader\fP"
.br
.ti -1c
.RI "\fBGUIEVENTS\fP \fBEvents\fP"
.br
.ti -1c
.RI "int \fBm_WindowWidth\fP"
.br
.ti -1c
.RI "int \fBm_WindowHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file GUI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
