.TH "GUIEVENTS" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIEVENTS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBMousePosition\fP [2]"
.br
.ti -1c
.RI "bool \fBKeyPressed\fP [256]"
.br
.ti -1c
.RI "bool \fBRightClickWasPressed\fP"
.br
.ti -1c
.RI "bool \fBLeftClickWasPressed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file Types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
