.TH "Input::Mouse" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input::Mouse \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMouseCallBack\fP (GLFWwindow *window, double xpos, double ypos)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBXPOS\fP = 500"
.br
.ti -1c
.RI "static double \fBYPOS\fP = 500"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Mouse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
