.TH "IO::Audio::Audio" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Audio::Audio \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddAudioElement\fP (int, std::shared_ptr< \fBAudioElement\fP > element)"
.br
.ti -1c
.RI "void \fBPlayAudio\fP ()"
.br
.ti -1c
.RI "void \fBPlayByID\fP (int)"
.br
.ti -1c
.RI "bool \fBsetMasterVolume\fP (float)"
.br
.ti -1c
.RI "bool \fBsetMusicVolume\fP (float)"
.br
.ti -1c
.RI "bool \fBsetGameVolume\fP (float)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_MasterVolume\fP"
.br
.ti -1c
.RI "float \fBm_MusicVolume\fP"
.br
.ti -1c
.RI "float \fBm_GameVolume\fP"
.br
.ti -1c
.RI "ALCdevice * \fBdevice\fP"
.br
.ti -1c
.RI "ALCcontext * \fBcontext\fP"
.br
.ti -1c
.RI "std::unordered_map< int, std::shared_ptr< \fBAudioElement\fP > > \fBm_AudioElementsCollection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Audio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
