.TH "IO::Filesystem::PhysicalFileSystem" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Filesystem::PhysicalFileSystem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIO::Filesystem::VirtualFileSystem\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBPhysicalFileSystem\fP (std::string)"
.br
.ti -1c
.RI "\fBFile\fP \fBFindFile\fP (const std::string)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 54 of file filesystem\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IO::Filesystem::PhysicalFileSystem::PhysicalFileSystem (std::string)\fC [private]\fP"
Second is the real filesystem, i\&.e\&. not contained within a zip file, a hard drive 
.PP
Definition at line 30 of file filesystem\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
