.TH "IO::Filesystem::ZipFileSystem" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Filesystem::ZipFileSystem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIO::Filesystem::VirtualFileSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZipFileSystem\fP (std::string)"
.br
.ti -1c
.RI "\fBFile\fP \fBFindFile\fP (const std::string)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file filesystem\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IO::Filesystem::ZipFileSystem::ZipFileSystem (std::string)"
Definition of the two types of file systems First is the definition of the filesystem contained within an uncompresed zip file 
.PP
Definition at line 19 of file filesystem\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
