.TH "IO::Image::TGA" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Image::TGA \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTGA\fP (const char *path)"
.br
.ti -1c
.RI "\fBLoadFile\fP (const char *path)"
.br
.ti -1c
.RI "\fBDestroy\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBmData\fP"
.br
.ti -1c
.RI "char * \fBmPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file TGA\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
