.TH "IO::Image::Image" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IO::Image::Image \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBIO::Image::Image\fP > \fBImage_ptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadFile\fP (const char *path, unsigned char *&data, int *outwidth, int *outheight, int *outchannels)"
.br
.ti -1c
.RI "void \fBLoadFile\fP (const char *path)"
.br
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBgetSizePNG\fP (const char *p, int *w, int *h, int *c)"
.br
.ti -1c
.RI "void \fBgetSizeBMP\fP (const char *p, int *w, int *h)"
.br
.ti -1c
.RI "void \fBgetSizeTGA\fP (const char *p, int *w, int *h)"
.br
.ti -1c
.RI "void \fBgetSizeDDS\fP (const char *p, int *w, int *h)"
.br
.ti -1c
.RI "bool \fBisLoaded\fP ()"
.br
.ti -1c
.RI "void \fBonLoad\fP (std::function< void()> f)"
.br
.ti -1c
.RI "unsigned char * \fBgetData\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::function< void()> \fBOnLoad\fP = nullptr"
.br
.ti -1c
.RI "std::shared_ptr< std::thread > \fBth1\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBmLoaded\fP = false"
.br
.ti -1c
.RI "unsigned char * \fBmData\fP = nullptr"
.br
.ti -1c
.RI "std::string \fBmPath\fP = ''"
.br
.ti -1c
.RI "int \fBmWidth\fP = 0"
.br
.ti -1c
.RI "int \fBmHeight\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Image\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
