.TH "LightProbe" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightProbe \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCaptureLight\fP ()"
.br
.ti -1c
.RI "void \fBFilterProve\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "glm::vec3 \fBm_Position\fP"
.br
.ti -1c
.RI "std::vector< glm::vec3 > \fBm_Directions\fP"
.br
.ti -1c
.RI "\fBCubeMap\fP \fBm_CubeMap\fP"
.br
.ti -1c
.RI "int \fBm_Width\fP"
.br
.ti -1c
.RI "int \fBm_Height\fP"
.br
.ti -1c
.RI "float \fBm_FOV\fP"
.br
.ti -1c
.RI "float \fBm_NearPlane\fP"
.br
.ti -1c
.RI "float \fBm_FarPlane\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file LightProbe\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
