.TH "Light" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLight\fP (short type, glm::vec3 direction, glm::vec3 position, float radius, float quadratic, float linear, float constant)"
.br
.ti -1c
.RI "short \fBgetType\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetDirection\fP ()"
.br
.ti -1c
.RI "glm::vec3 \fBgetPosition\fP ()"
.br
.ti -1c
.RI "float \fBgetRadius\fP ()"
.br
.ti -1c
.RI "float \fBgetQuadratic\fP ()"
.br
.ti -1c
.RI "float \fBgetLinear\fP ()"
.br
.ti -1c
.RI "float \fBgetConstant\fP ()"
.br
.ti -1c
.RI "\fBt_light\fP \fBtoStruct\fP ()"
.br
.ti -1c
.RI "void \fBsetType\fP (BYTE newType)"
.br
.ti -1c
.RI "void \fBsetDirection\fP (glm::vec3 newDirection)"
.br
.ti -1c
.RI "void \fBsetPosition\fP (glm::vec3 newPosition)"
.br
.ti -1c
.RI "void \fBsetRadius\fP (float newRadius)"
.br
.ti -1c
.RI "void \fBsetQuadratic\fP (float newQuadratic)"
.br
.ti -1c
.RI "void \fBsetLinear\fP (float newLinear)"
.br
.ti -1c
.RI "void \fBsetConstant\fP (float newConstant)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "short \fBtype\fP"
.br
.ti -1c
.RI "glm::vec3 \fBdirection\fP"
.br
.ti -1c
.RI "glm::vec3 \fBposition\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "float \fBquadratic\fP"
.br
.ti -1c
.RI "float \fBlinear\fP"
.br
.ti -1c
.RI "float \fBconstant\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 15 of file Light\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "short Light::getType ()\fC [inline]\fP"
Getters 
.PP
Definition at line 33 of file Light\&.h\&.
.SS "void Light::setType (BYTE newType)\fC [inline]\fP"
Setters 
.PP
Definition at line 75 of file Light\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
