.TH "Model::BOUNDING_BOX" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Model::BOUNDING_BOX \- Structure to store the models bounding box for visibility and collision computation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBFRONT_TOP_LEFT\fP"
.br
.ti -1c
.RI "float \fBFRONT_TOP_RIGHT\fP"
.br
.ti -1c
.RI "float \fBFRONT_BOTTOM_LEFT\fP"
.br
.ti -1c
.RI "float \fBFRONT_BOTTOM_RIGHT\fP"
.br
.ti -1c
.RI "float \fBBACK_TOP_LEFT\fP"
.br
.ti -1c
.RI "float \fBBACK_TOP_RIGHT\fP"
.br
.ti -1c
.RI "float \fBBACK_BOTTOM_LEFT\fP"
.br
.ti -1c
.RI "float \fBBACK_BOTTOM_RIGHT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store the models bounding box for visibility and collision computation\&. 
.PP
Definition at line 102 of file Model\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
