.TH "Physics::CubePhysicObject" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::CubePhysicObject \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhysics::PhysicObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (float, float, float, float, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (glm::vec3, float, \fBMIN_MAX_POINTS\fP, float)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (float, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (std::vector< glm::vec3 >, std::vector< unsigned int >, float)"
.br
.ti -1c
.RI "virtual std::shared_ptr< btRigidBody > \fBaddObject\fP (glm::vec3, float, float)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_Size\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBm_Mass\fP = 0\&.0f"
.br
.ti -1c
.RI "glm::vec3 \fBm_Position\fP = glm::vec3(0\&.0f, 0\&.0f, 0\&.0f)"
.br
.ti -1c
.RI "std::shared_ptr< btBoxShape > \fBCubeShape\fP"
.br
.ti -1c
.RI "std::shared_ptr< btMotionState > \fBmotionState\fP"
.br
.ti -1c
.RI "std::shared_ptr< btCompoundShape > \fBm_ColShape\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file CubePhysicObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
