.TH "Physics::CollisionInfo" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::CollisionInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string name)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_Name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file CollisionInfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
