.TH "Physics::Physics" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics::Physics \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (float)"
.br
.ti -1c
.RI "std::shared_ptr< btSoftRigidDynamicsWorld > \fBgetSoftDynamicsWorld\fP ()"
.br
.ti -1c
.RI "std::string \fBgetCollisionObjectName\fP (btVector3 rayPosition, btVector3 rayTarget)"
.br
.ti -1c
.RI "glm::vec3 \fBgetCollisionPosition\fP (btVector3 rayPosition, btVector3 rayTarget)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::shared_ptr< btDynamicsWorld > \fBworld\fP"
.br
.ti -1c
.RI "std::shared_ptr< btBroadphaseInterface > \fBbroadphase\fP"
.br
.ti -1c
.RI "std::shared_ptr< btSoftBodyWorldInfo > \fBsoftBodyWorldInfo\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< btDispatcher > \fBdispatcher\fP"
.br
.ti -1c
.RI "std::shared_ptr< btCollisionConfiguration > \fBcollisionConfig\fP"
.br
.ti -1c
.RI "std::shared_ptr< btConstraintSolver > \fBsolver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Physics\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
