.TH "Pick" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pick \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPick\fP (std::shared_ptr< btDynamicsWorld >)"
.br
.ti -1c
.RI "virtual void \fBCheckforPicking\fP (btVector3, btVector3, btScalar, std::shared_ptr< btDynamicsWorld >)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBpickObject\fP (btVector3, btVector3, std::shared_ptr< btDynamicsWorld >)"
.br
.ti -1c
.RI "virtual bool \fBmoveObject\fP ()"
.br
.ti -1c
.RI "virtual void \fBdeleteConstraint\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "btRigidBody * \fBm_pickedBody\fP"
.br
.ti -1c
.RI "btTypedConstraint * \fBm_pickedConstraint\fP"
.br
.ti -1c
.RI "std::shared_ptr< btDynamicsWorld > \fBm_WorldInstance\fP"
.br
.ti -1c
.RI "btVector3 \fBm_oldPickingPos\fP"
.br
.ti -1c
.RI "btVector3 \fBm_hitPos\fP"
.br
.ti -1c
.RI "btVector3 \fBrayTo\fP"
.br
.ti -1c
.RI "btVector3 \fBrayFrom\fP"
.br
.ti -1c
.RI "btScalar \fBm_oldPickingDist\fP"
.br
.ti -1c
.RI "bool \fBactive\fP = false"
.br
.ti -1c
.RI "int \fBm_savedState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Picking\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
