.TH "PostProcess::MotionBlur" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostProcess::MotionBlur \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPostProcess::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotionBlur\fP (int w, int h)"
.br
.ti -1c
.RI "virtual GLuint \fBApply\fP (GLuint, GLuint, double)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_Activated\fP"
.br
.ti -1c
.RI "float \fBm_Intesity\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file MotionBlur\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
