.TH "PostProcess::SSAO" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostProcess::SSAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPostProcess::Effect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSSAO\fP (int, int)"
.br
.ti -1c
.RI "virtual GLuint \fBApply\fP (GLuint, GLuint, glm::mat4 projection, glm::mat4 view)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBPrepareSSAOTexture\fP ()"
.br
.ti -1c
.RI "void \fBPrepareSSAOBlurTexture\fP ()"
.br
.ti -1c
.RI "void \fBPrepareRendomSamplingTexture\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBnoiseTexture\fP"
.br
.ti -1c
.RI "std::vector< glm::vec3 > \fBssaoKernel\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBShader\fP > \fBblurShader\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBFrameBuffer\fP< std::string > > \fBm_pFrameBufferBlur\fP"
.br
.ti -1c
.RI "std::vector< glm::vec3 > \fBssaoNoise\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file SSAO\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void PostProcess::SSAO::PrepareSSAOTexture ()"

.PP
 \fBSSAO\fP Specific Code ---------------------------------------- 
.PP
Definition at line 62 of file SSAO\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
