.TH "ProgramData" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgramData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgramData\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBWINDOW_WIDTH\fP"
.br
.ti -1c
.RI "int \fBWINDOW_HEIGHT\fP"
.br
.ti -1c
.RI "int \fBFULLSCREEN\fP"
.br
.ti -1c
.RI "float \fBANISOTROPY\fP"
.br
.ti -1c
.RI "int \fBMSAA_SAMPLES\fP"
.br
.ti -1c
.RI "int \fBMONITOR\fP"
.br
.ti -1c
.RI "int \fBVSYNC\fP"
.br
.ti -1c
.RI "int \fBSHADOWMAP_SIZE\fP"
.br
.ti -1c
.RI "bool \fBBLOOM\fP"
.br
.ti -1c
.RI "bool \fBSCREEN_SPACE_REFLECTIONS\fP"
.br
.ti -1c
.RI "int \fBSSR_QUALITY\fP"
.br
.ti -1c
.RI "bool \fBLIGHTSHAFTS\fP"
.br
.ti -1c
.RI "bool \fBCOMPRESSED_TEXTURES\fP"
.br
.ti -1c
.RI "bool \fBMOTION_BLUR\fP"
.br
.ti -1c
.RI "float \fBMOTION_BLUR_STRENGTH\fP"
.br
.ti -1c
.RI "bool \fBPARALLAX_OCLUSSION_MAPPING\fP"
.br
.ti -1c
.RI "bool \fBBOKEH_DOF\fP"
.br
.ti -1c
.RI "bool \fBCHROMATIC_ABERRATION\fP"
.br
.ti -1c
.RI "bool \fBFXAA\fP"
.br
.ti -1c
.RI "bool \fBHBAO\fP"
.br
.ti -1c
.RI "int \fBHBAO_QUALITY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 10 of file ProgramData\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProgramData::ProgramData ()"
========= Copyright Survtech, All rights reserved\&. ============//
.PP
Purpose: 
.PP
 
.PP
Definition at line 11 of file ProgramData\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
