.TH "SphericalHarmonics" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SphericalHarmonics \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSphericalHarmonicsFormat\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCalculateCohefficients\fP (GLuint cubemap, const unsigned int order)"
.br
.ti -1c
.RI "std::vector< glm::vec3 > \fBgetCohefficients\fP ()"
.br
.ti -1c
.RI "void \fBSaveCohefficients\fP ()"
.br
.ti -1c
.RI "\fBSphericalHarmonicsFormat\fP \fBtoStruct\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (unsigned inId)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBmCohefficientsNames\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsphericalHarmonicsEvaluateDirection\fP (float *result, int order, const glm::vec3 &dir, std::string why)"
.br
.ti -1c
.RI "void \fBsphericalHarmonicsAdd\fP (float *result, int order, const float *inputA, const float *inputB, std::string why)"
.br
.ti -1c
.RI "void \fBsphericalHarmonicsScale\fP (float *result, int order, const float *input, float scale, std::string why)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< glm::vec3 > \fBm_Cohefficients\fP"
.br
.ti -1c
.RI "float \fBm_scaleFactor\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_Position\fP"
.br
.ti -1c
.RI "unsigned \fBm_ID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SphericalHarmonics\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
