.TH "SphericalHarmonics::SphericalHarmonicsFormat" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SphericalHarmonics::SphericalHarmonicsFormat \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "glm::vec3 \fBu_L00\fP"
.br
.ti -1c
.RI "float \fBpadding0\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L1m1\fP"
.br
.ti -1c
.RI "float \fBpadding1\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L10\fP"
.br
.ti -1c
.RI "float \fBpadding2\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L11\fP"
.br
.ti -1c
.RI "float \fBpadding3\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L2m2\fP"
.br
.ti -1c
.RI "float \fBpadding4\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L2m1\fP"
.br
.ti -1c
.RI "float \fBpadding5\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L20\fP"
.br
.ti -1c
.RI "float \fBpadding6\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L21\fP"
.br
.ti -1c
.RI "float \fBpadding7\fP"
.br
.ti -1c
.RI "glm::vec3 \fBu_L22\fP"
.br
.ti -1c
.RI "float \fBpadding8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file SphericalHarmonics\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
