.TH "t_TexCoord" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_TexCoord \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBs\fP"
.br
.ti -1c
.RI "float \fBt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file emlFormat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
