.TH "tBSPVisData" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPVisData \- This stores the cluster data for the PVS's\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumOfClusters\fP"
.br
.ti -1c
.RI "int \fBbytesPerCluster\fP"
.br
.RI "\fIThe number of clusters\&. \fP"
.ti -1c
.RI "char * \fBpBitsets\fP"
.br
.RI "\fIThe amount of bytes (8 bits) in the cluster's bitset\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This stores the cluster data for the PVS's\&. 
.PP
Definition at line 152 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
