.TH "tBSPTexture" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPTexture \- This is our BSP texture structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstrName\fP [64]"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.RI "\fIThe name of the texture w/o the extension\&. \fP"
.ti -1c
.RI "int \fBcontents\fP"
.br
.ti -1c
.RI "int \fBtextureType\fP"
.br
.RI "\fIThe surface flags (unknown) \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is our BSP texture structure\&. 
.PP
Definition at line 86 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
