.TH "tBSPFace" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tBSPFace \- This is our BSP face structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtextureID\fP"
.br
.ti -1c
.RI "int \fBeffect\fP"
.br
.RI "\fIThe index into the texture array\&. \fP"
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "\fIThe index for the effects (or -1 = n/a) \fP"
.ti -1c
.RI "int \fBstartVertIndex\fP"
.br
.RI "\fI1=polygon, 2=patch, 3=mesh, 4=billboard \fP"
.ti -1c
.RI "int \fBnumOfVerts\fP"
.br
.RI "\fIThe starting index into this face's first vertex\&. \fP"
.ti -1c
.RI "int \fBstartIndex\fP"
.br
.RI "\fIThe number of vertices for this face\&. \fP"
.ti -1c
.RI "int \fBnumOfIndices\fP"
.br
.RI "\fIThe starting index into the indices array for this face\&. \fP"
.ti -1c
.RI "int \fBlightmapID\fP"
.br
.RI "\fIThe number of indices for this face\&. \fP"
.ti -1c
.RI "int \fBlMapCorner\fP [2]"
.br
.RI "\fIThe texture index for the lightmap\&. \fP"
.ti -1c
.RI "int \fBlMapSize\fP [2]"
.br
.RI "\fIThe face's lightmap corner in the image\&. \fP"
.ti -1c
.RI "\fBCVector3\fP \fBlMapPos\fP"
.br
.ti -1c
.RI "\fBCVector3\fP \fBlMapVecs\fP [2]"
.br
.ti -1c
.RI "\fBCVector3\fP \fBvNormal\fP"
.br
.ti -1c
.RI "int \fBsize\fP [2]"
.br
.RI "\fIThe face normal\&. \fP"
.ti -1c
.RI "glm::vec3 \fBlMapPos\fP"
.br
.RI "\fIThe size of the lightmap section\&. \fP"
.ti -1c
.RI "glm::vec3 \fBlMapVecs\fP [2]"
.br
.RI "\fIThe 3D origin of lightmap\&. \fP"
.ti -1c
.RI "glm::vec3 \fBvNormal\fP"
.br
.RI "\fIThe 3D space for s and t unit vectors\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is our BSP face structure\&. 
.PP
Definition at line 68 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
