.TH "Threading::Promise" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Threading::Promise \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPromise\fP (\fBLambda\fP l)"
.br
.ti -1c
.RI "void \fBthen\fP (\fBLambda\fP< void(\fBLambda\fP success, \fBLambda\fP faillure)> l)"
.br
.ti -1c
.RI "void \fBcatch\fP (\fBLambda\fP< void(std::string)> l)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBLambda\fP \fB_primary_function\fP"
.br
.ti -1c
.RI "\fBLambda\fP< void(\fBLambda\fP, \fBLambda\fP)> \fB_then_function\fP"
.br
.ti -1c
.RI "\fBLambda\fP< void(std::string)> \fB_catch_function\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Promise\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
