.TH "Thread::Job< T >" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread::Job< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBBegin\fP ()"
.br
.ti -1c
.RI "int \fBFinish\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< Thread > \fBmThread\fP"
.br
.ti -1c
.RI "std::function< T > \fBmFunction\fP"
.br
.ti -1c
.RI "T \fBfunctionType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Thread::Job< T >"

.PP
Definition at line 8 of file Job\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
