.TH "tVector3i" 3 "Wed Mar 6 2019" "Version 1.0" "Epsilon Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tVector3i \- This is our small number to compensate for float errors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is our small number to compensate for float errors\&. 

This is our integer vector structure 
.PP
Definition at line 27 of file BSP\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Epsilon Engine from the source code\&.
