PostProcess
GLuint PostProcess::colorBuffer
GLuint PostProcess::depthBuffer
GLuint PostProcess::hdrFBO
std::unique_ptr<Shader> PostProcess::shader
GLuint PostProcess::SSAOwidth
GLuint PostProcess::SSAOheight
GLuint PostProcess::ssaoFBO
GLuint PostProcess::ssaoBlurFBO
GLuint PostProcess::rboDepth
GLuint PostProcess::rDepth
GLuint PostProcess::quadVAO
GLuint PostProcess::quadVBO
GLuint PostProcess::sampler
GLuint PostProcess::intermediateFBO
GLuint PostProcess::DepthTexture
GLuint PostProcess::lowresFBO
float PostProcess::lastDepth
GLuint PostProcess::lowresTex
GLuint PostProcess::pingpongFBO[2][2]
GLuint PostProcess::pingpongColorbuffers[2][2]
GLuint PostProcess::pingpongDOF[2][2]
GLuint PostProcess::pingpongColorbuffersDOF[2][2]
GLuint PostProcess::DOFBuffer
glm::vec3 PostProcess::Sun
std::vector<glm::vec3> PostProcess::ssaoNoise
GLenum PostProcess::attachment_type
int PostProcess::width
int PostProcess::height
std::unique_ptr<Shader> PostProcess::SSAO
std::unique_ptr<Shader> PostProcess::blurSSAO
std::unique_ptr<Shader> PostProcess::finalImage
std::unique_ptr<Shader> PostProcess::blurBloom
std::vector<glm::vec3> PostProcess::LightPositions
std::vector<glm::vec3> PostProcess::ssaoKernel
G-Buffer texture samplers.
Referenced by setupSSAO, applySSAO.
GLuint PostProcess::noiseTexture
GLuint PostProcess::brightColorBuffer
GLuint PostProcess::gBuffer
GLuint PostProcess::gAlbedoSpec
GLuint PostProcess::gPositionDepth
GLuint PostProcess::gNormal
GLuint PostProcess::gExpensiveNormal
GLuint PostProcess::ssaoColorBuffer
GLuint PostProcess::ssaoColorBufferBlur
GLuint PostProcess::gWorldSpacePosition
GLuint PostProcess::m_exposure
PostProcess::PostProcess()
virtual PostProcess::~PostProcess()
void PostProcess::beginOffScreenrendering(void)
Attaches the off-screen rendering buffer
void PostProcess::endOffScreenRendering(void)
Disattaches the off-screen rendering buffer
void PostProcess::ShowFrame(glm::vec3, bool &hdr, std::unique_ptr< Camera > &cam, float exposure, std::unique_ptr< ShadowMap > &)
Render the output from the G-Buffer
References RenderQuad.
void PostProcess::applySSAO(std::unique_ptr< Camera > &cam)
Calculates the screen space ambient occlusion from the geometry
References ssaoKernel, RenderQuad.
void PostProcess::ShowPostProcessImage(float exposure, GLuint)
Render the post process image to the screen after the post-process effects has been applied
References blurImage, RenderQuad.
void PostProcess::LoadOffscreensShaders(void)
loads the shaders used for render off-screen and post process affects
void PostProcess::SetupFramebuffer(void)
Creates the framebuffer objects and attaches the proper textures
References SetupGBuffer, setupSSAO, SetupPingPongFBO.
void PostProcess::RenderQuad(void)
Renders a quad that fills the screen
Referenced by applySSAO, blurImage, applyAutoAxposure, ShowPostProcessImage, ShowFrame.
float PostProcess::lerp(float y1, float y2, float mu)
Lerp function to interpolate values
Referenced by setupSSAO, applyAutoAxposure.
void PostProcess::SetupGBuffer(void)
Creates the GBuffer and attaches the proper textures
Referenced by SetupFramebuffer.
void PostProcess::setupSSAO(void)
Creates the SSAO framebuffer and attaches the proper textures
References lerp, ssaoKernel.
Referenced by SetupFramebuffer.
GLuint PostProcess::blurImage(GLuint Buffer)
Blurs and image using a Gaussian Blur shader
References RenderQuad.
Referenced by ShowPostProcessImage.
void PostProcess::SetupPingPongFBO(void)
Set up buffers for blurring
Referenced by SetupFramebuffer.
void PostProcess::SetupPingPongDOF(void)
Set up buffers for blurring
GLfloat PostProcess::applyAutoAxposure(GLuint Buffer)
gets the luminicense from a texture
References RenderQuad, lerp.